# Build_total_raw_water_demand.R
# This programs reads the Excel Accounting files, WGLXXXX and StanXXXX to get metered data into a Tidy format for plotting
# Email from Mary:
# The pumping numbers are located:
# WGL Sum Tab column D
# Tani Summary Tab columns K and P (note that the historian for TTP didn't record from 10-19-2021 into November)
# Stan2021(4-Party) Meter Tab R - This is total outflow including FHL Bubbler and inflows to Tani, not adjusted to the 48-Inch which we use in the accounting, but for your purposes it may be better to use the unadjusted with the following deducted to get TTP inflow. 
#       FHL Bubbler: Stan2021(decree) Meter Out Tab column F
#       Tani Summary Tab column G (no inflows 2021)
#
# Another consideration, but no metered number is the actual backwash from the plants to the backwash ponds (we only have the meter number from the backwash ponds to WGL. If you think it will be useful the backwash from the ponds to WGL is located WGL Sum Tab column E.
# End of email from Mary
# The relevant files are copied from the Accounting share S:\ID\WR\Accounting\ to the Supply and Demand Planning share S:\ID\WR\Supply and Demand Planning\Demand Forecasting\demand\ to avoid the possibility of corrupting the historical Accounting files.
#
# Data is extracted in table format and then tidied using pivot_long.
# Load the necessary R libraries
#
library(dplyr)
library(readxl)
#
# Read the workbooks and create a new dataframe with the values from Excel.
#
# Load the data for January into dataframe dfrwfinal
dfrwjan1 <- read_excel("WGL2010.xlsm", sheet = "Sum", range = "A72:A102", col_names = "month_day")
dfrwjan1$month_day <- as.Date(as.character((dfrwjan1$month_day)))
dfrwjan2 <- read_excel("WGL2010.xlsm", sheet = "Sum", range = "D72:D102", col_names = "y_2010")
dfrwfinal <- cbind(dfrwjan1, dfrwjan2)
dfrwjan3 <- read_excel("WGL2011.xlsm", sheet = "Sum", range = "D72:D102", col_names = "y_2011")
dfrwfinal <- cbind(dfrwfinal, dfrwjan3)
dfrwjan4 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "D72:D102", col_names = "y_2012")
dfrwfinal <- cbind(dfrwfinal, dfrwjan4)
dfrwjan5 <- read_excel("WGL2013.xlsm", sheet = "Sum", range = "D72:D102", col_names = "y_2013")
dfrwfinal <- cbind(dfrwfinal, dfrwjan5)
dfrwjan6 <- read_excel("WGL2014.xlsm", sheet = "Sum", range = "D72:D102", col_names = "y_2014")
dfrwfinal <- cbind(dfrwfinal, dfrwjan6)
dfrwjan7 <- read_excel("WGL2015.xlsm", sheet = "Sum", range = "D72:D102", col_names = "y_2015")
dfrwfinal <- cbind(dfrwfinal, dfrwjan7)
dfrwjan8 <- read_excel("WGL2016.xlsm", sheet = "Sum", range = "D72:D102", col_names = "y_2016")
dfrwfinal <- cbind(dfrwfinal, dfrwjan8)
dfrwjan9 <- read_excel("WGL2017.xlsm", sheet = "Sum", range = "D72:D102", col_names = "y_2017")
dfrwfinal <- cbind(dfrwfinal, dfrwjan9)
dfrwjan10 <- read_excel("WGL2018.xlsm", sheet = "Sum", range = "D72:D102", col_names = "y_2018")
dfrwfinal <- cbind(dfrwfinal, dfrwjan10)
dfrwjan11 <- read_excel("WGL2019.xlsm", sheet = "Sum", range = "D72:D102", col_names = "y_2019")
dfrwfinal <- cbind(dfrwfinal, dfrwjan11)
dfrwjan12 <- read_excel("WGL2020.xlsm", sheet = "Sum", range = "D72:D102", col_names = "y_2020")
dfrwfinal <- cbind(dfrwfinal, dfrwjan12)
dfrwjan13 <- read_excel("WGL2021.xlsm", sheet = "Sum", range = "D72:D102", col_names = "y_2021")
dfrwfinal <- cbind(dfrwfinal, dfrwjan13)
#
# Load the data for February into dataframe dfrwfinal
dfrwfeb1 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "A104:A132", col_names = "month_day")
dfrwfeb1$month_day <- as.Date(as.character((dfrwfeb1$month_day)))
dfrwfeb2 <- read_excel("WGL2010.xlsm", sheet = "Sum", range = "D104:D132", col_names = "y_2010")
dfrwfeb <- cbind(dfrwfeb1, dfrwfeb2)
dfrwfeb3 <- read_excel("WGL2011.xlsm", sheet = "Sum", range = "D104:D132", col_names = "y_2011")
dfrwfeb <- cbind(dfrwfeb, dfrwfeb3)
dfrwfeb4 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "D104:D132", col_names = "y_2012")
dfrwfeb <- cbind(dfrwfeb, dfrwfeb4)
dfrwfeb5 <- read_excel("WGL2013.xlsm", sheet = "Sum", range = "D104:D132", col_names = "y_2013")
dfrwfeb <- cbind(dfrwfeb, dfrwfeb5)
dfrwfeb6 <- read_excel("WGL2014.xlsm", sheet = "Sum", range = "D104:D132", col_names = "y_2014")
dfrwfeb <- cbind(dfrwfeb, dfrwfeb6)
dfrwfeb7 <- read_excel("WGL2015.xlsm", sheet = "Sum", range = "D104:D132", col_names = "y_2015")
dfrwfeb <- cbind(dfrwfeb, dfrwfeb7)
dfrwfeb8 <- read_excel("WGL2016.xlsm", sheet = "Sum", range = "D104:D132", col_names = "y_2016")
dfrwfeb <- cbind(dfrwfeb, dfrwfeb8)
dfrwfeb9 <- read_excel("WGL2017.xlsm", sheet = "Sum", range = "D104:D132", col_names = "y_2017")
dfrwfeb <- cbind(dfrwfeb, dfrwfeb9)
dfrwfeb10 <- read_excel("WGL2018.xlsm", sheet = "Sum", range = "D104:D132", col_names = "y_2018")
dfrwfeb <- cbind(dfrwfeb, dfrwfeb10)
dfrwfeb11 <- read_excel("WGL2019.xlsm", sheet = "Sum", range = "D104:D132", col_names = "y_2019")
dfrwfeb <- cbind(dfrwfeb, dfrwfeb11)
dfrwfeb12 <- read_excel("WGL2020.xlsm", sheet = "Sum", range = "D104:D132", col_names = "y_2020")
dfrwfeb <- cbind(dfrwfeb, dfrwfeb12)
dfrwfeb13 <- read_excel("WGL2021.xlsm", sheet = "Sum", range = "D104:D132", col_names = "y_2021")
dfrwfeb <- cbind(dfrwfeb, dfrwfeb13)
#
dfrwfinal <- rbind(dfrwfinal, dfrwfeb)
#
# Load the data for March into dataframe dfrwfinal
dfrwmar1 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "A134:A164", col_names = "month_day")
dfrwmar1$month_day <- as.Date(as.character((dfrwmar1$month_day)))
dfrwmar2 <- read_excel("WGL2010.xlsm", sheet = "Sum", range = "D134:D164", col_names = "y_2010")
dfrwmar <- cbind(dfrwmar1, dfrwmar2)
dfrwmar3 <- read_excel("WGL2011.xlsm", sheet = "Sum", range = "D134:D164", col_names = "y_2011")
dfrwmar <- cbind(dfrwmar, dfrwmar3)
dfrwmar4 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "D134:D164", col_names = "y_2012")
dfrwmar <- cbind(dfrwmar, dfrwmar4)
dfrwmar5 <- read_excel("WGL2013.xlsm", sheet = "Sum", range = "D134:D164", col_names = "y_2013")
dfrwmar <- cbind(dfrwmar, dfrwmar5)
dfrwmar6 <- read_excel("WGL2014.xlsm", sheet = "Sum", range = "D134:D164", col_names = "y_2014")
dfrwmar <- cbind(dfrwmar, dfrwmar6)
dfrwmar7 <- read_excel("WGL2015.xlsm", sheet = "Sum", range = "D134:D164", col_names = "y_2015")
dfrwmar <- cbind(dfrwmar, dfrwmar7)
dfrwmar8 <- read_excel("WGL2016.xlsm", sheet = "Sum", range = "D134:D164", col_names = "y_2016")
dfrwmar <- cbind(dfrwmar, dfrwmar8)
dfrwmar9 <- read_excel("WGL2017.xlsm", sheet = "Sum", range = "D134:D164", col_names = "y_2017")
dfrwmar <- cbind(dfrwmar, dfrwmar9)
dfrwmar10 <- read_excel("WGL2018.xlsm", sheet = "Sum", range = "D134:D164", col_names = "y_2018")
dfrwmar <- cbind(dfrwmar, dfrwmar10)
dfrwmar11 <- read_excel("WGL2019.xlsm", sheet = "Sum", range = "D134:D164", col_names = "y_2019")
dfrwmar <- cbind(dfrwmar, dfrwmar11)
dfrwmar12 <- read_excel("WGL2020.xlsm", sheet = "Sum", range = "D134:D164", col_names = "y_2020")
dfrwmar <- cbind(dfrwmar, dfrwmar12)
dfrwmar13 <- read_excel("WGL2021.xlsm", sheet = "Sum", range = "D134:D164", col_names = "y_2021")
dfrwmar <- cbind(dfrwmar, dfrwmar13)
#
dfrwfinal <- rbind(dfrwfinal, dfrwmar)
#
# Load the data for April into dataframe dfrwfinal
dfrwapr1 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "A166:A195", col_names = "month_day")
dfrwapr1$month_day <- as.Date(as.character((dfrwapr1$month_day)))
dfrwapr2 <- read_excel("WGL2010.xlsm", sheet = "Sum", range = "D166:D195", col_names = "y_2010")
dfrwapr <- cbind(dfrwapr1, dfrwapr2)
dfrwapr3 <- read_excel("WGL2011.xlsm", sheet = "Sum", range = "D166:D195", col_names = "y_2011")
dfrwapr <- cbind(dfrwapr, dfrwapr3)
dfrwapr4 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "D166:D195", col_names = "y_2012")
dfrwapr <- cbind(dfrwapr, dfrwapr4)
dfrwapr5 <- read_excel("WGL2013.xlsm", sheet = "Sum", range = "D166:D195", col_names = "y_2013")
dfrwapr <- cbind(dfrwapr, dfrwapr5)
dfrwapr6 <- read_excel("WGL2014.xlsm", sheet = "Sum", range = "D166:D195", col_names = "y_2014")
dfrwapr <- cbind(dfrwapr, dfrwapr6)
dfrwapr7 <- read_excel("WGL2015.xlsm", sheet = "Sum", range = "D166:D195", col_names = "y_2015")
dfrwapr <- cbind(dfrwapr, dfrwapr7)
dfrwapr8 <- read_excel("WGL2016.xlsm", sheet = "Sum", range = "D166:D195", col_names = "y_2016")
dfrwapr <- cbind(dfrwapr, dfrwapr8)
dfrwapr9 <- read_excel("WGL2017.xlsm", sheet = "Sum", range = "D166:D195", col_names = "y_2017")
dfrwapr <- cbind(dfrwapr, dfrwapr9)
dfrwapr10 <- read_excel("WGL2018.xlsm", sheet = "Sum", range = "D166:D195", col_names = "y_2018")
dfrwapr <- cbind(dfrwapr, dfrwapr10)
dfrwapr11 <- read_excel("WGL2019.xlsm", sheet = "Sum", range = "D166:D195", col_names = "y_2019")
dfrwapr <- cbind(dfrwapr, dfrwapr11)
dfrwapr12 <- read_excel("WGL2020.xlsm", sheet = "Sum", range = "D166:D195", col_names = "y_2020")
dfrwapr <- cbind(dfrwapr, dfrwapr12)
dfrwapr13 <- read_excel("WGL2021.xlsm", sheet = "Sum", range = "D166:D195", col_names = "y_2021")
dfrwapr <- cbind(dfrwapr, dfrwapr13)
#
dfrwfinal <- rbind(dfrwfinal, dfrwapr)
#
# Load the data for May into dataframe dfrwfinal
dfrwmay1 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "A197:A227", col_names = "month_day")
dfrwmay1$month_day <- as.Date(as.character((dfrwmay1$month_day)))
dfrwmay2 <- read_excel("WGL2010.xlsm", sheet = "Sum", range = "D197:D227", col_names = "y_2010")
dfrwmay <- cbind(dfrwmay1, dfrwmay2)
dfrwmay3 <- read_excel("WGL2011.xlsm", sheet = "Sum", range = "D197:D227", col_names = "y_2011")
dfrwmay <- cbind(dfrwmay, dfrwmay3)
dfrwmay4 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "D197:D227", col_names = "y_2012")
dfrwmay <- cbind(dfrwmay, dfrwmay4)
dfrwmay5 <- read_excel("WGL2013.xlsm", sheet = "Sum", range = "D197:D227", col_names = "y_2013")
dfrwmay <- cbind(dfrwmay, dfrwmay5)
dfrwmay6 <- read_excel("WGL2014.xlsm", sheet = "Sum", range = "D197:D227", col_names = "y_2014")
dfrwmay <- cbind(dfrwmay, dfrwmay6)
dfrwmay7 <- read_excel("WGL2015.xlsm", sheet = "Sum", range = "D197:D227", col_names = "y_2015")
dfrwmay <- cbind(dfrwmay, dfrwmay7)
dfrwmay8 <- read_excel("WGL2016.xlsm", sheet = "Sum", range = "D197:D227", col_names = "y_2016")
dfrwmay <- cbind(dfrwmay, dfrwmay8)
dfrwmay9 <- read_excel("WGL2017.xlsm", sheet = "Sum", range = "D197:D227", col_names = "y_2017")
dfrwmay <- cbind(dfrwmay, dfrwmay9)
dfrwmay10 <- read_excel("WGL2018.xlsm", sheet = "Sum", range = "D197:D227", col_names = "y_2018")
dfrwmay <- cbind(dfrwmay, dfrwmay10)
dfrwmay11 <- read_excel("WGL2019.xlsm", sheet = "Sum", range = "D197:D227", col_names = "y_2019")
dfrwmay <- cbind(dfrwmay, dfrwmay11)
dfrwmay12 <- read_excel("WGL2020.xlsm", sheet = "Sum", range = "D197:D227", col_names = "y_2020")
dfrwmay <- cbind(dfrwmay, dfrwmay12)
dfrwmay13 <- read_excel("WGL2021.xlsm", sheet = "Sum", range = "D197:D227", col_names = "y_2021")
dfrwmay <- cbind(dfrwmay, dfrwmay13)
#
dfrwfinal <- rbind(dfrwfinal, dfrwmay)
#
# Load the data for June into dataframe dfrwfinal
dfrwjun1 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "A229:A258", col_names = "month_day")
dfrwjun1$month_day <- as.Date(as.character((dfrwjun1$month_day)))
dfrwjun2 <- read_excel("WGL2010.xlsm", sheet = "Sum", range = "D229:D258", col_names = "y_2010")
dfrwjun <- cbind(dfrwjun1, dfrwjun2)
dfrwjun3 <- read_excel("WGL2011.xlsm", sheet = "Sum", range = "D229:D258", col_names = "y_2011")
dfrwjun <- cbind(dfrwjun, dfrwjun3)
dfrwjun4 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "D229:D258", col_names = "y_2012")
dfrwjun <- cbind(dfrwjun, dfrwjun4)
dfrwjun5 <- read_excel("WGL2013.xlsm", sheet = "Sum", range = "D229:D258", col_names = "y_2013")
dfrwjun <- cbind(dfrwjun, dfrwjun5)
dfrwjun6 <- read_excel("WGL2014.xlsm", sheet = "Sum", range = "D229:D258", col_names = "y_2014")
dfrwjun <- cbind(dfrwjun, dfrwjun6)
dfrwjun7 <- read_excel("WGL2015.xlsm", sheet = "Sum", range = "D229:D258", col_names = "y_2015")
dfrwjun <- cbind(dfrwjun, dfrwjun7)
dfrwjun8 <- read_excel("WGL2016.xlsm", sheet = "Sum", range = "D229:D258", col_names = "y_2016")
dfrwjun <- cbind(dfrwjun, dfrwjun8)
dfrwjun9 <- read_excel("WGL2017.xlsm", sheet = "Sum", range = "D229:D258", col_names = "y_2017")
dfrwjun <- cbind(dfrwjun, dfrwjun9)
dfrwjun10 <- read_excel("WGL2018.xlsm", sheet = "Sum", range = "D229:D258", col_names = "y_2018")
dfrwjun <- cbind(dfrwjun, dfrwjun10)
dfrwjun11 <- read_excel("WGL2019.xlsm", sheet = "Sum", range = "D229:D258", col_names = "y_2019")
dfrwjun <- cbind(dfrwjun, dfrwjun11)
dfrwjun12 <- read_excel("WGL2020.xlsm", sheet = "Sum", range = "D229:D258", col_names = "y_2020")
dfrwjun <- cbind(dfrwjun, dfrwjun12)
dfrwjun13 <- read_excel("WGL2021.xlsm", sheet = "Sum", range = "D229:D258", col_names = "y_2021")
dfrwjun <- cbind(dfrwjun, dfrwjun13)
#
dfrwfinal <- rbind(dfrwfinal, dfrwjun)
#
# Load the data for July into dataframe dfrwfinal
dfrwjul1 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "A260:A290", col_names = "month_day")
dfrwjul1$month_day <- as.Date(as.character((dfrwjul1$month_day)))
dfrwjul2 <- read_excel("WGL2010.xlsm", sheet = "Sum", range = "D260:D290", col_names = "y_2010")
dfrwjul <- cbind(dfrwjul1, dfrwjul2)
dfrwjul3 <- read_excel("WGL2011.xlsm", sheet = "Sum", range = "D260:D290", col_names = "y_2011")
dfrwjul <- cbind(dfrwjul, dfrwjul3)
dfrwjul4 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "D260:D290", col_names = "y_2012")
dfrwjul <- cbind(dfrwjul, dfrwjul4)
dfrwjul5 <- read_excel("WGL2013.xlsm", sheet = "Sum", range = "D260:D290", col_names = "y_2013")
dfrwjul <- cbind(dfrwjul, dfrwjul5)
dfrwjul6 <- read_excel("WGL2014.xlsm", sheet = "Sum", range = "D260:D290", col_names = "y_2014")
dfrwjul <- cbind(dfrwjul, dfrwjul6)
dfrwjul7 <- read_excel("WGL2015.xlsm", sheet = "Sum", range = "D260:D290", col_names = "y_2015")
dfrwjul <- cbind(dfrwjul, dfrwjul7)
dfrwjul8 <- read_excel("WGL2016.xlsm", sheet = "Sum", range = "D260:D290", col_names = "y_2016")
dfrwjul <- cbind(dfrwjul, dfrwjul8)
dfrwjul9 <- read_excel("WGL2017.xlsm", sheet = "Sum", range = "D260:D290", col_names = "y_2017")
dfrwjul <- cbind(dfrwjul, dfrwjul9)
dfrwjul10 <- read_excel("WGL2018.xlsm", sheet = "Sum", range = "D260:D290", col_names = "y_2018")
dfrwjul <- cbind(dfrwjul, dfrwjul10)
dfrwjul11 <- read_excel("WGL2019.xlsm", sheet = "Sum", range = "D260:D290", col_names = "y_2019")
dfrwjul <- cbind(dfrwjul, dfrwjul11)
dfrwjul12 <- read_excel("WGL2020.xlsm", sheet = "Sum", range = "D260:D290", col_names = "y_2020")
dfrwjul <- cbind(dfrwjul, dfrwjul12)
dfrwjul13 <- read_excel("WGL2021.xlsm", sheet = "Sum", range = "D260:D290", col_names = "y_2021")
dfrwjul <- cbind(dfrwjul, dfrwjul13)
#
dfrwfinal <- rbind(dfrwfinal, dfrwjul)
#
# Load the data for August into dataframe dfrwfinal
dfrwaug1 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "A292:A322", col_names = "month_day")
dfrwaug1$month_day <- as.Date(as.character((dfrwaug1$month_day)))
dfrwaug2 <- read_excel("WGL2010.xlsm", sheet = "Sum", range = "D292:D322", col_names = "y_2010")
dfrwaug <- cbind(dfrwaug1, dfrwaug2)
dfrwaug3 <- read_excel("WGL2011.xlsm", sheet = "Sum", range = "D292:D322", col_names = "y_2011")
dfrwaug <- cbind(dfrwaug, dfrwaug3)
dfrwaug4 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "D292:D322", col_names = "y_2012")
dfrwaug <- cbind(dfrwaug, dfrwaug4)
dfrwaug5 <- read_excel("WGL2013.xlsm", sheet = "Sum", range = "D292:D322", col_names = "y_2013")
dfrwaug <- cbind(dfrwaug, dfrwaug5)
dfrwaug6 <- read_excel("WGL2014.xlsm", sheet = "Sum", range = "D292:D322", col_names = "y_2014")
dfrwaug <- cbind(dfrwaug, dfrwaug6)
dfrwaug7 <- read_excel("WGL2015.xlsm", sheet = "Sum", range = "D292:D322", col_names = "y_2015")
dfrwaug <- cbind(dfrwaug, dfrwaug7)
dfrwaug8 <- read_excel("WGL2016.xlsm", sheet = "Sum", range = "D292:D322", col_names = "y_2016")
dfrwaug <- cbind(dfrwaug, dfrwaug8)
dfrwaug9 <- read_excel("WGL2017.xlsm", sheet = "Sum", range = "D292:D322", col_names = "y_2017")
dfrwaug <- cbind(dfrwaug, dfrwaug9)
dfrwaug10 <- read_excel("WGL2018.xlsm", sheet = "Sum", range = "D292:D322", col_names = "y_2018")
dfrwaug <- cbind(dfrwaug, dfrwaug10)
dfrwaug11 <- read_excel("WGL2019.xlsm", sheet = "Sum", range = "D292:D322", col_names = "y_2019")
dfrwaug <- cbind(dfrwaug, dfrwaug11)
dfrwaug12 <- read_excel("WGL2020.xlsm", sheet = "Sum", range = "D292:D322", col_names = "y_2020")
dfrwaug <- cbind(dfrwaug, dfrwaug12)
dfrwaug13 <- read_excel("WGL2021.xlsm", sheet = "Sum", range = "D292:D322", col_names = "y_2021")
dfrwaug <- cbind(dfrwaug, dfrwaug13)
#
dfrwfinal <- rbind(dfrwfinal, dfrwaug)
#
# Load the data for September into dataframe dfrwfinal
dfrwsep1 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "A324:A353", col_names = "month_day")
dfrwsep1$month_day <- as.Date(as.character((dfrwsep1$month_day)))
dfrwsep2 <- read_excel("WGL2010.xlsm", sheet = "Sum", range = "D324:D353", col_names = "y_2010")
dfrwsep <- cbind(dfrwsep1, dfrwsep2)
dfrwsep3 <- read_excel("WGL2011.xlsm", sheet = "Sum", range = "D324:D353", col_names = "y_2011")
dfrwsep <- cbind(dfrwsep, dfrwsep3)
dfrwsep4 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "D324:D353", col_names = "y_2012")
dfrwsep <- cbind(dfrwsep, dfrwsep4)
dfrwsep5 <- read_excel("WGL2013.xlsm", sheet = "Sum", range = "D324:D353", col_names = "y_2013")
dfrwsep <- cbind(dfrwsep, dfrwsep5)
dfrwsep6 <- read_excel("WGL2014.xlsm", sheet = "Sum", range = "D324:D353", col_names = "y_2014")
dfrwsep <- cbind(dfrwsep, dfrwsep6)
dfrwsep7 <- read_excel("WGL2015.xlsm", sheet = "Sum", range = "D324:D353", col_names = "y_2015")
dfrwsep <- cbind(dfrwsep, dfrwsep7)
dfrwsep8 <- read_excel("WGL2016.xlsm", sheet = "Sum", range = "D324:D353", col_names = "y_2016")
dfrwsep <- cbind(dfrwsep, dfrwsep8)
dfrwsep9 <- read_excel("WGL2017.xlsm", sheet = "Sum", range = "D324:D353", col_names = "y_2017")
dfrwsep <- cbind(dfrwsep, dfrwsep9)
dfrwsep10 <- read_excel("WGL2018.xlsm", sheet = "Sum", range = "D324:D353", col_names = "y_2018")
dfrwsep <- cbind(dfrwsep, dfrwsep10)
dfrwsep11 <- read_excel("WGL2019.xlsm", sheet = "Sum", range = "D324:D353", col_names = "y_2019")
dfrwsep <- cbind(dfrwsep, dfrwsep11)
dfrwsep12 <- read_excel("WGL2020.xlsm", sheet = "Sum", range = "D324:D353", col_names = "y_2020")
dfrwsep <- cbind(dfrwsep, dfrwsep12)
dfrwsep13 <- read_excel("WGL2021.xlsm", sheet = "Sum", range = "D324:D353", col_names = "y_2021")
dfrwsep <- cbind(dfrwsep, dfrwsep13)
#
dfrwfinal <- rbind(dfrwfinal, dfrwsep)
#
# Load the data for October into dataframe dfrwfinal
# NOte: I copied the formats from the October range of cells A355:L385 into the WGL2011.xlsm workbook. read_excel would not return values from column D. This seemed to work as the read from WGL2011.xlsm now works.
dfrwoct1 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "A355:A385", col_names = "month_day")
dfrwoct1$month_day <- as.Date(as.character((dfrwoct1$month_day)))
dfrwoct2 <- read_excel("WGL2010.xlsm", sheet = "Sum", range = "D355:D385", col_names = "y_2010")
dfrwoct <- cbind(dfrwoct1, dfrwoct2)
dfrwoct3 <- read_excel("WGL2011.xlsm", sheet = "Sum", range = "D355:D385", col_names = "y_2011")
dfrwoct <- cbind(dfrwoct, dfrwoct3)
dfrwoct4 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "D355:D385", col_names = "y_2012")
dfrwoct <- cbind(dfrwoct, dfrwoct4)
dfrwoct5 <- read_excel("WGL2013.xlsm", sheet = "Sum", range = "D355:D385", col_names = "y_2013")
dfrwoct <- cbind(dfrwoct, dfrwoct5)
dfrwoct6 <- read_excel("WGL2014.xlsm", sheet = "Sum", range = "D355:D385", col_names = "y_2014")
dfrwoct <- cbind(dfrwoct, dfrwoct6)
dfrwoct7 <- read_excel("WGL2015.xlsm", sheet = "Sum", range = "D355:D385", col_names = "y_2015")
dfrwoct <- cbind(dfrwoct, dfrwoct7)
dfrwoct8 <- read_excel("WGL2016.xlsm", sheet = "Sum", range = "D355:D385", col_names = "y_2016")
dfrwoct <- cbind(dfrwoct, dfrwoct8)
dfrwoct9 <- read_excel("WGL2017.xlsm", sheet = "Sum", range = "D355:D385", col_names = "y_2017")
dfrwoct <- cbind(dfrwoct, dfrwoct9)
dfrwoct10 <- read_excel("WGL2018.xlsm", sheet = "Sum", range = "D355:D385", col_names = "y_2018")
dfrwoct <- cbind(dfrwoct, dfrwoct10)
dfrwoct11 <- read_excel("WGL2019.xlsm", sheet = "Sum", range = "D355:D385", col_names = "y_2019")
dfrwoct <- cbind(dfrwoct, dfrwoct11)
dfrwoct12 <- read_excel("WGL2020.xlsm", sheet = "Sum", range = "D355:D385", col_names = "y_2020")
dfrwoct <- cbind(dfrwoct, dfrwoct12)
dfrwoct13 <- read_excel("WGL2021.xlsm", sheet = "Sum", range = "D355:D385", col_names = "y_2021")
dfrwoct <- cbind(dfrwoct, dfrwoct13)
#
dfrwfinal <- rbind(dfrwfinal, dfrwoct)
#
#
# Load the data for November into dataframe dfrwfinal. NOTE that the workbooks conform to the DWR water year and therefore run from November in one year through October the following year, so in order to get November and December for e.g. "2010" you need the WGL2011 workbook.
dfrwnov1 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "A9:A38", col_names = "month_day")
dfrwnov1$month_day <- as.Date(as.character((dfrwnov1$month_day)))
dfrwnov2 <- read_excel("WGL2011.xlsm", sheet = "Sum", range = "D9:D38", col_names = "y_2010")
dfrwnov <- cbind(dfrwnov1, dfrwnov2)
dfrwnov3 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "D9:D38", col_names = "y_2011")
dfrwnov <- cbind(dfrwnov, dfrwnov3)
dfrwnov4 <- read_excel("WGL2013.xlsm", sheet = "Sum", range = "D9:D38", col_names = "y_2012")
dfrwnov <- cbind(dfrwnov, dfrwnov4)
dfrwnov5 <- read_excel("WGL2014.xlsm", sheet = "Sum", range = "D9:D38", col_names = "y_2013")
dfrwnov <- cbind(dfrwnov, dfrwnov5)
dfrwnov6 <- read_excel("WGL2015.xlsm", sheet = "Sum", range = "D9:D38", col_names = "y_2014")
dfrwnov <- cbind(dfrwnov, dfrwnov6)
dfrwnov7 <- read_excel("WGL2016.xlsm", sheet = "Sum", range = "D9:D38", col_names = "y_2015")
dfrwnov <- cbind(dfrwnov, dfrwnov7)
dfrwnov8 <- read_excel("WGL2017.xlsm", sheet = "Sum", range = "D9:D38", col_names = "y_2016")
dfrwnov <- cbind(dfrwnov, dfrwnov8)
dfrwnov9 <- read_excel("WGL2018.xlsm", sheet = "Sum", range = "D9:D38", col_names = "y_2017")
dfrwnov <- cbind(dfrwnov, dfrwnov9)
dfrwnov10 <- read_excel("WGL2019.xlsm", sheet = "Sum", range = "D9:D38", col_names = "y_2018")
dfrwnov <- cbind(dfrwnov, dfrwnov10)
dfrwnov11 <- read_excel("WGL2020.xlsm", sheet = "Sum", range = "D9:D38", col_names = "y_2019")
dfrwnov <- cbind(dfrwnov, dfrwnov11)
dfrwnov12 <- read_excel("WGL2021.xlsm", sheet = "Sum", range = "D9:D38", col_names = "y_2020")
dfrwnov <- cbind(dfrwnov, dfrwnov12)
dfrwnov13 <- read_excel("WGL2022.xlsm", sheet = "Sum", range = "D9:D38", col_names = "y_2021")
dfrwnov <- cbind(dfrwnov, dfrwnov13)
#
# Load the data for December into dataframe dfrwfinal. NOTE that the workbooks conform to the DWR water year and therefore run from November in one year through October the following year, so in order to get November and December for e.g. "2010" you need the WGL2011 workbook.
dfrwdec1 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "A40:A70", col_names = "month_day")
dfrwdec1$month_day <- as.Date(as.character((dfrwdec1$month_day)))
dfrwdec2 <- read_excel("WGL2011.xlsm", sheet = "Sum", range = "D40:D70", col_names = "y_2010")
dfrwdec <- cbind(dfrwdec1, dfrwdec2)
dfrwdec3 <- read_excel("WGL2012.xlsm", sheet = "Sum", range = "D40:D70", col_names = "y_2011")
dfrwdec <- cbind(dfrwdec, dfrwdec3)
dfrwdec4 <- read_excel("WGL2013.xlsm", sheet = "Sum", range = "D40:D70", col_names = "y_2012")
dfrwdec <- cbind(dfrwdec, dfrwdec4)
dfrwdec5 <- read_excel("WGL2014.xlsm", sheet = "Sum", range = "D40:D70", col_names = "y_2013")
dfrwdec <- cbind(dfrwdec, dfrwdec5)
dfrwdec6 <- read_excel("WGL2015.xlsm", sheet = "Sum", range = "D40:D70", col_names = "y_2014")
dfrwdec <- cbind(dfrwdec, dfrwdec6)
dfrwdec7 <- read_excel("WGL2016.xlsm", sheet = "Sum", range = "D40:D70", col_names = "y_2015")
dfrwdec <- cbind(dfrwdec, dfrwdec7)
dfrwdec8 <- read_excel("WGL2017.xlsm", sheet = "Sum", range = "D40:D70", col_names = "y_2016")
dfrwdec <- cbind(dfrwdec, dfrwdec8)
dfrwdec9 <- read_excel("WGL2018.xlsm", sheet = "Sum", range = "D40:D70", col_names = "y_2017")
dfrwdec <- cbind(dfrwdec, dfrwdec9)
dfrwdec10 <- read_excel("WGL2019.xlsm", sheet = "Sum", range = "D40:D70", col_names = "y_2018")
dfrwdec <- cbind(dfrwdec, dfrwdec10)
dfrwdec11 <- read_excel("WGL2020.xlsm", sheet = "Sum", range = "D40:D70", col_names = "y_2019")
dfrwdec <- cbind(dfrwdec, dfrwdec11)
dfrwdec12 <- read_excel("WGL2021.xlsm", sheet = "Sum", range = "D40:D70", col_names = "y_2020")
dfrwdec <- cbind(dfrwdec, dfrwdec12)
dfrwdec13 <- read_excel("WGL2022.xlsm", sheet = "Sum", range = "D40:D70", col_names = "y_2021")
dfrwdec <- cbind(dfrwdec, dfrwdec13)
#

dfrwfinal <- rbind(dfrwfinal, dfrwdec)
#

# The values from the workbooks are negative, change them to positive. They are inflows to the treatment plant and come in negative because they are outflows from the reservoir.
# 
dfrwfinal[, 2:13] <- dfrwfinal[, 2:13] * -1
#
# Replace all NA values with 0
#
dfrwfinal[, 2:13] <- lapply(dfrwfinal[, 2:13], function(x) replace(x, is.na(x), 0))
#
# Compute the mean for each day over all the years ignoring zeros
#
dfrwfinal$mean = apply(dfrwfinal[, 2:13], 1, function(x) mean(x[x>0]))
#
# Computing the mean on February 29th with all zero values for WGL  returns NaN. Hoping that this will clear up when there are not treatment values = 0 with all workbooks.
# 
# Compute the median for each day over all the years ignoring zeros
#
dfrwfinal$median = apply(dfrwfinal[, 2:13], 1, function(x) median(x[x>0]))
#
# Computing the median on February 29th with all zero values for WGL  returns NA. Hoping that this will clear up when there are not treatment values = 0 with all workbooks.
#
# Determine the maximum by day over all of the days ignoring zeros
dfrwfinal$maximum <- apply(dfrwfinal[, 2:13], 1, function(x) max(x[x>=0]))
# 
# Determine the maximum by day over all of the days ignoring zeros
dfrwfinal$minimum <- apply(dfrwfinal[, 2:13], 1, function(x) min(x[x>=0]))
#
# Used during testing
View(dfrwfinal)
#
# Write the dataframe to a .csv file
# write.csv(dfrwfinal,'dfrwfinal.csv', row.names = FALSE)
#
# Free up memory
# rm(list = ls())
# gc()
# Read the workbooks and create a new dataframe with the values from Excel. I had to unlock the "Taniwith ESP2010.xlsm" column H for read_excel to return values. Also I checked "Show a zero in cells that have zero value". Save the file for changes to take effects. For some workbooks I had to enter zeroes in columns that had blank cells.
#
# Load the data for January into dataframe dfrwtanifinal
dfrwtanijan1 <- read_excel("TANIwith ESP2010.xlsm", sheet = "Summary", range = "A72:A102", col_names = "month_day")
dfrwtanijan1$month_day <- as.Date(as.character((dfrwtanijan1$month_day)))
dfrwtanijan2 <- read_excel("TANIwith ESP2010.xlsm", sheet = "Summary", range = "H72:H102", col_names = "y_2010")
dfrwtanifinal <- cbind(dfrwtanijan1, dfrwtanijan2)
dfrwtanijan3 <- read_excel("TANIwith ESP2011.xlsm", sheet = "Summary", range = "H72:H102", col_names = "y_2011")
dfrwtanifinal <- cbind(dfrwtanifinal, dfrwtanijan3)
dfrwtanijan4 <- read_excel("TANIwith ESP2012.xlsm", sheet = "Summary", range = "I72:I102", col_names = "y_2012")
dfrwtanifinal <- cbind(dfrwtanifinal, dfrwtanijan4)
dfrwtanijan5 <- read_excel("TANIwith ESP2013.xlsm", sheet = "Summary", range = "I72:I102", col_names = "y_2013")
dfrwtanifinal <- cbind(dfrwtanifinal, dfrwtanijan5)
dfrwtanijan6 <- read_excel("TANIwith ESP2014.xlsm", sheet = "Summary", range = "I72:I102", col_names = "y_2014")
dfrwtanifinal <- cbind(dfrwtanifinal, dfrwtanijan6)
dfrwtanijan7 <- read_excel("TANIwith ESP2015.xlsm", sheet = "Summary", range = "I72:I102", col_names = "y_2015")
dfrwtanifinal <- cbind(dfrwtanifinal, dfrwtanijan7)
dfrwtanijan8 <- read_excel("TANIwith ESP2016.xlsm", sheet = "Summary", range = "I72:I102", col_names = "y_2016")
dfrwtanifinal <- cbind(dfrwtanifinal, dfrwtanijan8)
dfrwtanijan9 <- read_excel("TANIwith ESP2017.xlsm", sheet = "Summary", range = "I72:I102", col_names = "y_2017")
dfrwtanifinal <- cbind(dfrwtanifinal, dfrwtanijan9)
dfrwtanijan10 <- read_excel("TANIwithWSP2018.xlsm", sheet = "Summary", range = "K72:K102", col_names = "y_2018")
dfrwtanifinal <- cbind(dfrwtanifinal, dfrwtanijan10)
dfrwtanijan11 <- read_excel("TANIwithWSP2019.xlsm", sheet = "Summary", range = "K72:K102", col_names = "y_2019")
dfrwtanifinal <- cbind(dfrwtanifinal, dfrwtanijan11)
dfrwtanijan12 <- read_excel("TANIwithWSP2020.xlsm", sheet = "Summary", range = "K72:K102", col_names = "y_2020")
dfrwtanifinal <- cbind(dfrwtanifinal, dfrwtanijan12)
dfrwtanijan13 <- read_excel("TANIwithWSP2021.xlsm", sheet = "Summary", range = "K72:K102", col_names = "y_2021")
dfrwtanifinal <- cbind(dfrwtanifinal, dfrwtanijan13)
#
# Load the data for February into dataframe dfrwtanifinal
dfrwtanifeb1 <- read_excel("TANIwith ESP2010.xlsm", sheet = "Summary", range = "A104:A132", col_names = "month_day")
dfrwtanifeb1$month_day <- as.Date(as.character((dfrwtanifeb1$month_day)))
dfrwtanifeb2 <- read_excel("TANIwith ESP2010.xlsm", sheet = "Summary", range = "H104:H132", col_names = "y_2010")
dfrwtanifeb <- cbind(dfrwtanifeb1, dfrwtanifeb2)
dfrwtanifeb3 <- read_excel("TANIwith ESP2011.xlsm", sheet = "Summary", range = "H104:H132", col_names = "y_2011")
dfrwtanifeb <- cbind(dfrwtanifeb, dfrwtanifeb3)
dfrwtanifeb4 <- read_excel("TANIwith ESP2012.xlsm", sheet = "Summary", range = "I104:I132", col_names = "y_2012")
dfrwtanifeb <- cbind(dfrwtanifeb, dfrwtanifeb4)
dfrwtanifeb5 <- read_excel("TANIwith ESP2013.xlsm", sheet = "Summary", range = "I104:I132", col_names = "y_2013")
dfrwtanifeb <- cbind(dfrwtanifeb, dfrwtanifeb5)
dfrwtanifeb6 <- read_excel("TANIwith ESP2014.xlsm", sheet = "Summary", range = "I104:I132", col_names = "y_2014")
dfrwtanifeb <- cbind(dfrwtanifeb, dfrwtanifeb6)
dfrwtanifeb7 <- read_excel("TANIwith ESP2015.xlsm", sheet = "Summary", range = "I104:I132", col_names = "y_2015")
dfrwtanifeb <- cbind(dfrwtanifeb, dfrwtanifeb7)
dfrwtanifeb8 <- read_excel("TANIwith ESP2016.xlsm", sheet = "Summary", range = "I104:I132", col_names = "y_2016")
dfrwtanifeb <- cbind(dfrwtanifeb, dfrwtanifeb8)
dfrwtanifeb9 <- read_excel("TANIwith ESP2017.xlsm", sheet = "Summary", range = "I104:I132", col_names = "y_2017")
dfrwtanifeb <- cbind(dfrwtanifeb, dfrwtanifeb9)
dfrwtanifeb10 <- read_excel("TANIwithWSP2018.xlsm", sheet = "Summary", range = "K104:K132", col_names = "y_2018")
dfrwtanifeb <- cbind(dfrwtanifeb, dfrwtanifeb10)
dfrwtanifeb11 <- read_excel("TANIwithWSP2019.xlsm", sheet = "Summary", range = "K104:K132", col_names = "y_2019")
dfrwtanifeb <- cbind(dfrwtanifeb, dfrwtanifeb11)
dfrwtanifeb12 <- read_excel("TANIwithWSP2020.xlsm", sheet = "Summary", range = "K104:K132", col_names = "y_2020")
dfrwtanifeb <- cbind(dfrwtanifeb, dfrwtanifeb12)
dfrwtanifeb13 <- read_excel("TANIwithWSP2021.xlsm", sheet = "Summary", range = "K104:K132", col_names = "y_2021")
dfrwtanifeb <- cbind(dfrwtanifeb, dfrwtanifeb13)
#
dfrwtanifinal <- rbind(dfrwtanifinal, dfrwtanifeb)
#
# Load the data for March into dataframe dfrwtanifinal
dfrwtanimar1 <- read_excel("TANIwith ESP2010.xlsm", sheet = "Summary", range = "A134:A164", col_names = "month_day")
dfrwtanimar1$month_day <- as.Date(as.character((dfrwtanimar1$month_day)))
dfrwtanimar2 <- read_excel("TANIwith ESP2010.xlsm", sheet = "Summary", range = "H134:H164", col_names = "y_2010")
dfrwtanimar <- cbind(dfrwtanimar1, dfrwtanimar2)
dfrwtanimar3 <- read_excel("TANIwith ESP2011.xlsm", sheet = "Summary", range = "H134:H164", col_names = "y_2011")
dfrwtanimar <- cbind(dfrwtanimar, dfrwtanimar3)
dfrwtanimar4 <- read_excel("TANIwith ESP2012.xlsm", sheet = "Summary", range = "I134:I164", col_names = "y_2012")
dfrwtanimar <- cbind(dfrwtanimar, dfrwtanimar4)
dfrwtanimar5 <- read_excel("TANIwith ESP2013.xlsm", sheet = "Summary", range = "I134:I164", col_names = "y_2013")
dfrwtanimar <- cbind(dfrwtanimar, dfrwtanimar5)
dfrwtanimar6 <- read_excel("TANIwith ESP2014.xlsm", sheet = "Summary", range = "I134:I164", col_names = "y_2014")
dfrwtanimar <- cbind(dfrwtanimar, dfrwtanimar6)
dfrwtanimar7 <- read_excel("TANIwith ESP2015.xlsm", sheet = "Summary", range = "I134:I164", col_names = "y_2015")
dfrwtanimar <- cbind(dfrwtanimar, dfrwtanimar7)
dfrwtanimar8 <- read_excel("TANIwith ESP2016.xlsm", sheet = "Summary", range = "I134:I164", col_names = "y_2016")
dfrwtanimar <- cbind(dfrwtanimar, dfrwtanimar8)
dfrwtanimar9 <- read_excel("TANIwith ESP2017.xlsm", sheet = "Summary", range = "I134:I164", col_names = "y_2017")
dfrwtanimar <- cbind(dfrwtanimar, dfrwtanimar9)
dfrwtanimar10 <- read_excel("TANIwithWSP2018.xlsm", sheet = "Summary", range = "K134:K164", col_names = "y_2018")
dfrwtanimar <- cbind(dfrwtanimar, dfrwtanimar10)
dfrwtanimar11 <- read_excel("TANIwithWSP2019.xlsm", sheet = "Summary", range = "K134:K164", col_names = "y_2019")
dfrwtanimar <- cbind(dfrwtanimar, dfrwtanimar11)
dfrwtanimar12 <- read_excel("TANIwithWSP2020.xlsm", sheet = "Summary", range = "K134:K164", col_names = "y_2020")
dfrwtanimar <- cbind(dfrwtanimar, dfrwtanimar12)
dfrwtanimar13 <- read_excel("TANIwithWSP2021.xlsm", sheet = "Summary", range = "K134:K164", col_names = "y_2021")
dfrwtanimar <- cbind(dfrwtanimar, dfrwtanimar13)
#
dfrwtanifinal <- rbind(dfrwtanifinal, dfrwtanimar)
#
# Load the data for March into dataframe dfrwtanifinal
dfrwtanimar1 <- read_excel("TANIwith ESP2010.xlsm", sheet = "Summary", range = "A134:A164", col_names = "month_day")
dfrwtanimar1$month_day <- as.Date(as.character((dfrwtanimar1$month_day)))
dfrwtanimar2 <- read_excel("TANIwith ESP2010.xlsm", sheet = "Summary", range = "H134:H164", col_names = "y_2010")
dfrwtanimar <- cbind(dfrwtanimar1, dfrwtanimar2)
dfrwtanimar3 <- read_excel("TANIwith ESP2011.xlsm", sheet = "Summary", range = "H134:H164", col_names = "y_2011")
dfrwtanimar <- cbind(dfrwtanimar, dfrwtanimar3)
dfrwtanimar4 <- read_excel("TANIwith ESP2012.xlsm", sheet = "Summary", range = "I134:I164", col_names = "y_2012")
dfrwtanimar <- cbind(dfrwtanimar, dfrwtanimar4)
dfrwtanimar5 <- read_excel("TANIwith ESP2013.xlsm", sheet = "Summary", range = "I134:I164", col_names = "y_2013")
dfrwtanimar <- cbind(dfrwtanimar, dfrwtanimar5)
dfrwtanimar6 <- read_excel("TANIwith ESP2014.xlsm", sheet = "Summary", range = "I134:I164", col_names = "y_2014")
dfrwtanimar <- cbind(dfrwtanimar, dfrwtanimar6)
dfrwtanimar7 <- read_excel("TANIwith ESP2015.xlsm", sheet = "Summary", range = "I134:I164", col_names = "y_2015")
dfrwtanimar <- cbind(dfrwtanimar, dfrwtanimar7)
dfrwtanimar8 <- read_excel("TANIwith ESP2016.xlsm", sheet = "Summary", range = "I134:I164", col_names = "y_2016")
dfrwtanimar <- cbind(dfrwtanimar, dfrwtanimar8)
dfrwtanimar9 <- read_excel("TANIwith ESP2017.xlsm", sheet = "Summary", range = "I134:I164", col_names = "y_2017")
dfrwtanimar <- cbind(dfrwtanimar, dfrwtanimar9)
dfrwtanimar10 <- read_excel("TANIwithWSP2018.xlsm", sheet = "Summary", range = "K134:K164", col_names = "y_2018")
dfrwtanimar <- cbind(dfrwtanimar, dfrwtanimar10)
dfrwtanimar11 <- read_excel("TANIwithWSP2019.xlsm", sheet = "Summary", range = "K134:K164", col_names = "y_2019")
dfrwtanimar <- cbind(dfrwtanimar, dfrwtanimar11)
dfrwtanimar12 <- read_excel("TANIwithWSP2020.xlsm", sheet = "Summary", range = "K134:K164", col_names = "y_2020")
dfrwtanimar <- cbind(dfrwtanimar, dfrwtanimar12)
dfrwtanimar13 <- read_excel("TANIwithWSP2021.xlsm", sheet = "Summary", range = "K134:K164", col_names = "y_2021")
dfrwtanimar <- cbind(dfrwtanimar, dfrwtanimar13)
#
dfrwtanifinal <- rbind(dfrwtanifinal, dfrwtanimar)
#
# Load the data for April into dataframe dfrwtanifinal
dfrwtaniapr1 <- read_excel("TANIwith ESP2010.xlsm", sheet = "Summary", range = "A166:A195", col_names = "month_day")
dfrwtaniapr1$month_day <- as.Date(as.character((dfrwtaniapr1$month_day)))
dfrwtaniapr2 <- read_excel("TANIwith ESP2010.xlsm", sheet = "Summary", range = "H166:H195", col_names = "y_2010")
dfrwtaniapr <- cbind(dfrwtaniapr1, dfrwtaniapr2)
dfrwtaniapr3 <- read_excel("TANIwith ESP2011.xlsm", sheet = "Summary", range = "H166:H195", col_names = "y_2011")
dfrwtaniapr <- cbind(dfrwtaniapr, dfrwtaniapr3)
dfrwtaniapr4 <- read_excel("TANIwith ESP2012.xlsm", sheet = "Summary", range = "I166:I195", col_names = "y_2012")
dfrwtaniapr <- cbind(dfrwtaniapr, dfrwtaniapr4)
dfrwtaniapr5 <- read_excel("TANIwith ESP2013.xlsm", sheet = "Summary", range = "I166:I195", col_names = "y_2013")
dfrwtaniapr <- cbind(dfrwtaniapr, dfrwtaniapr5)
dfrwtaniapr6 <- read_excel("TANIwith ESP2014.xlsm", sheet = "Summary", range = "I166:I195", col_names = "y_2014")
dfrwtaniapr <- cbind(dfrwtaniapr, dfrwtaniapr6)
dfrwtaniapr7 <- read_excel("TANIwith ESP2015.xlsm", sheet = "Summary", range = "I166:I195", col_names = "y_2015")
dfrwtaniapr <- cbind(dfrwtaniapr, dfrwtaniapr7)
dfrwtaniapr8 <- read_excel("TANIwith ESP2016.xlsm", sheet = "Summary", range = "I166:I195", col_names = "y_2016")
dfrwtaniapr <- cbind(dfrwtaniapr, dfrwtaniapr8)
dfrwtaniapr9 <- read_excel("TANIwith ESP2017.xlsm", sheet = "Summary", range = "I166:I195", col_names = "y_2017")
dfrwtaniapr <- cbind(dfrwtaniapr, dfrwtaniapr9)
dfrwtaniapr10 <- read_excel("TANIwithWSP2018.xlsm", sheet = "Summary", range = "K166:K195", col_names = "y_2018")
dfrwtaniapr <- cbind(dfrwtaniapr, dfrwtaniapr10)
dfrwtaniapr11 <- read_excel("TANIwithWSP2019.xlsm", sheet = "Summary", range = "K166:K195", col_names = "y_2019")
dfrwtaniapr <- cbind(dfrwtaniapr, dfrwtaniapr11)
dfrwtaniapr12 <- read_excel("TANIwithWSP2020.xlsm", sheet = "Summary", range = "K166:K195", col_names = "y_2020")
dfrwtaniapr <- cbind(dfrwtaniapr, dfrwtaniapr12)
dfrwtaniapr13 <- read_excel("TANIwithWSP2021.xlsm", sheet = "Summary", range = "K166:K195", col_names = "y_2021")
dfrwtaniapr <- cbind(dfrwtaniapr, dfrwtaniapr13)
#
dfrwtanifinal <- rbind(dfrwtanifinal, dfrwtaniapr)
#
# Load the data for May into dataframe dfrwtanifinal
dfrwtanimay1 <- read_excel("TANIwith ESP2010.xlsm", sheet = "Summary", range = "A197:A227", col_names = "month_day")
dfrwtanimay1$month_day <- as.Date(as.character((dfrwtanimay1$month_day)))
dfrwtanimay2 <- read_excel("TANIwith ESP2010.xlsm", sheet = "Summary", range = "H197:H227", col_names = "y_2010")
dfrwtanimay <- cbind(dfrwtanimay1, dfrwtanimay2)
dfrwtanimay3 <- read_excel("TANIwith ESP2011.xlsm", sheet = "Summary", range = "H197:H227", col_names = "y_2011")
dfrwtanimay <- cbind(dfrwtanimay, dfrwtanimay3)
dfrwtanimay4 <- read_excel("TANIwith ESP2012.xlsm", sheet = "Summary", range = "I197:I227", col_names = "y_2012")
dfrwtanimay <- cbind(dfrwtanimay, dfrwtanimay4)
dfrwtanimay5 <- read_excel("TANIwith ESP2013.xlsm", sheet = "Summary", range = "I197:I227", col_names = "y_2013")
dfrwtanimay <- cbind(dfrwtanimay, dfrwtanimay5)
dfrwtanimay6 <- read_excel("TANIwith ESP2014.xlsm", sheet = "Summary", range = "I197:I227", col_names = "y_2014")
dfrwtanimay <- cbind(dfrwtanimay, dfrwtanimay6)
dfrwtanimay7 <- read_excel("TANIwith ESP2015.xlsm", sheet = "Summary", range = "I197:I227", col_names = "y_2015")
dfrwtanimay <- cbind(dfrwtanimay, dfrwtanimay7)
dfrwtanimay8 <- read_excel("TANIwith ESP2016.xlsm", sheet = "Summary", range = "I197:I227", col_names = "y_2016")
dfrwtanimay <- cbind(dfrwtanimay, dfrwtanimay8)
dfrwtanimay9 <- read_excel("TANIwith ESP2017.xlsm", sheet = "Summary", range = "I197:I227", col_names = "y_2017")
dfrwtanimay <- cbind(dfrwtanimay, dfrwtanimay9)
dfrwtanimay10 <- read_excel("TANIwithWSP2018.xlsm", sheet = "Summary", range = "K197:K227", col_names = "y_2018")
dfrwtanimay <- cbind(dfrwtanimay, dfrwtanimay10)
dfrwtanimay11 <- read_excel("TANIwithWSP2019.xlsm", sheet = "Summary", range = "K197:K227", col_names = "y_2019")
dfrwtanimay <- cbind(dfrwtanimay, dfrwtanimay11)
dfrwtanimay12 <- read_excel("TANIwithWSP2020.xlsm", sheet = "Summary", range = "K197:K227", col_names = "y_2020")
dfrwtanimay <- cbind(dfrwtanimay, dfrwtanimay12)
dfrwtanimay13 <- read_excel("TANIwithWSP2021.xlsm", sheet = "Summary", range = "K197:K227", col_names = "y_2021")
dfrwtanimay <- cbind(dfrwtanimay, dfrwtanimay13)
#
dfrwtanifinal <- rbind(dfrwtanifinal, dfrwtanimay)
#
# Load the data for June into dataframe dfrwtanifinal
dfrwtanijun1 <- read_excel("TANIwith ESP2010.xlsm", sheet = "Summary", range = "A229:A258", col_names = "month_day")
dfrwtanijun1$month_day <- as.Date(as.character((dfrwtanijun1$month_day)))
dfrwtanijun2 <- read_excel("TANIwith ESP2010.xlsm", sheet = "Summary", range = "H229:H258", col_names = "y_2010")
dfrwtanijun <- cbind(dfrwtanijun1, dfrwtanijun2)
dfrwtanijun3 <- read_excel("TANIwith ESP2011.xlsm", sheet = "Summary", range = "H229:H258", col_names = "y_2011")
dfrwtanijun <- cbind(dfrwtanijun, dfrwtanijun3)
dfrwtanijun4 <- read_excel("TANIwith ESP2012.xlsm", sheet = "Summary", range = "I229:I258", col_names = "y_2012")
dfrwtanijun <- cbind(dfrwtanijun, dfrwtanijun4)
dfrwtanijun5 <- read_excel("TANIwith ESP2013.xlsm", sheet = "Summary", range = "I229:I258", col_names = "y_2013")
dfrwtanijun <- cbind(dfrwtanijun, dfrwtanijun5)
dfrwtanijun6 <- read_excel("TANIwith ESP2014.xlsm", sheet = "Summary", range = "I229:I258", col_names = "y_2014")
dfrwtanijun <- cbind(dfrwtanijun, dfrwtanijun6)
dfrwtanijun7 <- read_excel("TANIwith ESP2015.xlsm", sheet = "Summary", range = "I229:I258", col_names = "y_2015")
dfrwtanijun <- cbind(dfrwtanijun, dfrwtanijun7)
dfrwtanijun8 <- read_excel("TANIwith ESP2016.xlsm", sheet = "Summary", range = "I229:I258", col_names = "y_2016")
dfrwtanijun <- cbind(dfrwtanijun, dfrwtanijun8)
dfrwtanijun9 <- read_excel("TANIwith ESP2017.xlsm", sheet = "Summary", range = "I229:I258", col_names = "y_2017")
dfrwtanijun <- cbind(dfrwtanijun, dfrwtanijun9)
dfrwtanijun10 <- read_excel("TANIwithWSP2018.xlsm", sheet = "Summary", range = "K229:K258", col_names = "y_2018")
dfrwtanijun <- cbind(dfrwtanijun, dfrwtanijun10)
dfrwtanijun11 <- read_excel("TANIwithWSP2019.xlsm", sheet = "Summary", range = "K229:K258", col_names = "y_2019")
dfrwtanijun <- cbind(dfrwtanijun, dfrwtanijun11)
dfrwtanijun12 <- read_excel("TANIwithWSP2020.xlsm", sheet = "Summary", range = "K229:K258", col_names = "y_2020")
dfrwtanijun <- cbind(dfrwtanijun, dfrwtanijun12)
dfrwtanijun13 <- read_excel("TANIwithWSP2021.xlsm", sheet = "Summary", range = "K229:K258", col_names = "y_2021")
dfrwtanijun <- cbind(dfrwtanijun, dfrwtanijun13)
#
dfrwtanifinal <- rbind(dfrwtanifinal, dfrwtanijun)
#
# Load the data for July into dataframe dfrwtanifinal
dfrwtanijul1 <- read_excel("TANIwith ESP2010.xlsm", sheet = "Summary", range = "A260:A290", col_names = "month_day")
dfrwtanijul1$month_day <- as.Date(as.character((dfrwtanijul1$month_day)))
dfrwtanijul2 <- read_excel("TANIwith ESP2010.xlsm", sheet = "Summary", range = "H260:H290", col_names = "y_2010")
dfrwtanijul <- cbind(dfrwtanijul1, dfrwtanijul2)
dfrwtanijul3 <- read_excel("TANIwith ESP2011.xlsm", sheet = "Summary", range = "H260:H290", col_names = "y_2011")
dfrwtanijul <- cbind(dfrwtanijul, dfrwtanijul3)
dfrwtanijul4 <- read_excel("TANIwith ESP2012.xlsm", sheet = "Summary", range = "I260:I290", col_names = "y_2012")
dfrwtanijul <- cbind(dfrwtanijul, dfrwtanijul4)
dfrwtanijul5 <- read_excel("TANIwith ESP2013.xlsm", sheet = "Summary", range = "I260:I290", col_names = "y_2013")
dfrwtanijul <- cbind(dfrwtanijul, dfrwtanijul5)
dfrwtanijul6 <- read_excel("TANIwith ESP2014.xlsm", sheet = "Summary", range = "I260:I290", col_names = "y_2014")
dfrwtanijul <- cbind(dfrwtanijul, dfrwtanijul6)
dfrwtanijul7 <- read_excel("TANIwith ESP2015.xlsm", sheet = "Summary", range = "I260:I290", col_names = "y_2015")
dfrwtanijul <- cbind(dfrwtanijul, dfrwtanijul7)
dfrwtanijul8 <- read_excel("TANIwith ESP2016.xlsm", sheet = "Summary", range = "I260:I290", col_names = "y_2016")
dfrwtanijul <- cbind(dfrwtanijul, dfrwtanijul8)
dfrwtanijul9 <- read_excel("TANIwith ESP2017.xlsm", sheet = "Summary", range = "I260:I290", col_names = "y_2017")
dfrwtanijul <- cbind(dfrwtanijul, dfrwtanijul9)
dfrwtanijul10 <- read_excel("TANIwithWSP2018.xlsm", sheet = "Summary", range = "K260:K290", col_names = "y_2018")
dfrwtanijul <- cbind(dfrwtanijul, dfrwtanijul10)
dfrwtanijul11 <- read_excel("TANIwithWSP2019.xlsm", sheet = "Summary", range = "K260:K290", col_names = "y_2019")
dfrwtanijul <- cbind(dfrwtanijul, dfrwtanijul11)
dfrwtanijul12 <- read_excel("TANIwithWSP2020.xlsm", sheet = "Summary", range = "K260:K290", col_names = "y_2020")
dfrwtanijul <- cbind(dfrwtanijul, dfrwtanijul12)
dfrwtanijul13 <- read_excel("TANIwithWSP2021.xlsm", sheet = "Summary", range = "K260:K290", col_names = "y_2021")
dfrwtanijul <- cbind(dfrwtanijul, dfrwtanijul13)
#
dfrwtanifinal <- rbind(dfrwtanifinal, dfrwtanijul)
#
# Load the data for August into dataframe dfrwtanifinal
dfrwtaniaug1 <- read_excel("TANIwith ESP2010.xlsm", sheet = "Summary", range = "A292:A322", col_names = "month_day")
dfrwtaniaug1$month_day <- as.Date(as.character((dfrwtaniaug1$month_day)))
dfrwtaniaug2 <- read_excel("TANIwith ESP2010.xlsm", sheet = "Summary", range = "H292:H322", col_names = "y_2010")
dfrwtaniaug <- cbind(dfrwtaniaug1, dfrwtaniaug2)
dfrwtaniaug3 <- read_excel("TANIwith ESP2011.xlsm", sheet = "Summary", range = "H292:H322", col_names = "y_2011")
dfrwtaniaug <- cbind(dfrwtaniaug, dfrwtaniaug3)
dfrwtaniaug4 <- read_excel("TANIwith ESP2012.xlsm", sheet = "Summary", range = "I292:I322", col_names = "y_2012")
dfrwtaniaug <- cbind(dfrwtaniaug, dfrwtaniaug4)
dfrwtaniaug5 <- read_excel("TANIwith ESP2013.xlsm", sheet = "Summary", range = "I292:I322", col_names = "y_2013")
dfrwtaniaug <- cbind(dfrwtaniaug, dfrwtaniaug5)
dfrwtaniaug6 <- read_excel("TANIwith ESP2014.xlsm", sheet = "Summary", range = "I292:I322", col_names = "y_2014")
dfrwtaniaug <- cbind(dfrwtaniaug, dfrwtaniaug6)
dfrwtaniaug7 <- read_excel("TANIwith ESP2015.xlsm", sheet = "Summary", range = "I292:I322", col_names = "y_2015")
dfrwtaniaug <- cbind(dfrwtaniaug, dfrwtaniaug7)
dfrwtaniaug8 <- read_excel("TANIwith ESP2016.xlsm", sheet = "Summary", range = "I292:I322", col_names = "y_2016")
dfrwtaniaug <- cbind(dfrwtaniaug, dfrwtaniaug8)
dfrwtaniaug9 <- read_excel("TANIwith ESP2017.xlsm", sheet = "Summary", range = "I292:I322", col_names = "y_2017")
dfrwtaniaug <- cbind(dfrwtaniaug, dfrwtaniaug9)
dfrwtaniaug10 <- read_excel("TANIwithWSP2018.xlsm", sheet = "Summary", range = "K292:K322", col_names = "y_2018")
dfrwtaniaug <- cbind(dfrwtaniaug, dfrwtaniaug10)
dfrwtaniaug11 <- read_excel("TANIwithWSP2019.xlsm", sheet = "Summary", range = "K292:K322", col_names = "y_2019")
dfrwtaniaug <- cbind(dfrwtaniaug, dfrwtaniaug11)
dfrwtaniaug12 <- read_excel("TANIwithWSP2020.xlsm", sheet = "Summary", range = "K292:K322", col_names = "y_2020")
dfrwtaniaug <- cbind(dfrwtaniaug, dfrwtaniaug12)
dfrwtaniaug13 <- read_excel("TANIwithWSP2021.xlsm", sheet = "Summary", range = "K292:K322", col_names = "y_2021")
dfrwtaniaug <- cbind(dfrwtaniaug, dfrwtaniaug13)
#
dfrwtanifinal <- rbind(dfrwtanifinal, dfrwtaniaug)
#
# Load the data for September into dataframe dfrwtanifinal
dfrwtanisep1 <- read_excel("TANIwith ESP2010.xlsm", sheet = "Summary", range = "A324:A353", col_names = "month_day")
dfrwtanisep1$month_day <- as.Date(as.character((dfrwtanisep1$month_day)))
dfrwtanisep2 <- read_excel("TANIwith ESP2010.xlsm", sheet = "Summary", range = "H324:H353", col_names = "y_2010")
dfrwtanisep <- cbind(dfrwtanisep1, dfrwtanisep2)
dfrwtanisep3 <- read_excel("TANIwith ESP2011.xlsm", sheet = "Summary", range = "H324:H353", col_names = "y_2011")
dfrwtanisep <- cbind(dfrwtanisep, dfrwtanisep3)
dfrwtanisep4 <- read_excel("TANIwith ESP2012.xlsm", sheet = "Summary", range = "I324:I353", col_names = "y_2012")
dfrwtanisep <- cbind(dfrwtanisep, dfrwtanisep4)
dfrwtanisep5 <- read_excel("TANIwith ESP2013.xlsm", sheet = "Summary", range = "I324:I353", col_names = "y_2013")
dfrwtanisep <- cbind(dfrwtanisep, dfrwtanisep5)
dfrwtanisep6 <- read_excel("TANIwith ESP2014.xlsm", sheet = "Summary", range = "I324:I353", col_names = "y_2014")
dfrwtanisep <- cbind(dfrwtanisep, dfrwtanisep6)
dfrwtanisep7 <- read_excel("TANIwith ESP2015.xlsm", sheet = "Summary", range = "I324:I353", col_names = "y_2015")
dfrwtanisep <- cbind(dfrwtanisep, dfrwtanisep7)
dfrwtanisep8 <- read_excel("TANIwith ESP2016.xlsm", sheet = "Summary", range = "I324:I353", col_names = "y_2016")
dfrwtanisep <- cbind(dfrwtanisep, dfrwtanisep8)
dfrwtanisep9 <- read_excel("TANIwith ESP2017.xlsm", sheet = "Summary", range = "I324:I353", col_names = "y_2017")
dfrwtanisep <- cbind(dfrwtanisep, dfrwtanisep9)
dfrwtanisep10 <- read_excel("TANIwithWSP2018.xlsm", sheet = "Summary", range = "K324:K353", col_names = "y_2018")
dfrwtanisep <- cbind(dfrwtanisep, dfrwtanisep10)
dfrwtanisep11 <- read_excel("TANIwithWSP2019.xlsm", sheet = "Summary", range = "K324:K353", col_names = "y_2019")
dfrwtanisep <- cbind(dfrwtanisep, dfrwtanisep11)
dfrwtanisep12 <- read_excel("TANIwithWSP2020.xlsm", sheet = "Summary", range = "K324:K353", col_names = "y_2020")
dfrwtanisep <- cbind(dfrwtanisep, dfrwtanisep12)
dfrwtanisep13 <- read_excel("TANIwithWSP2021.xlsm", sheet = "Summary", range = "K324:K353", col_names = "y_2021")
dfrwtanisep <- cbind(dfrwtanisep, dfrwtanisep13)
#
dfrwtanifinal <- rbind(dfrwtanifinal, dfrwtanisep)
#
# Load the data for October into dataframe dfrwtanifinal
dfrwtanioct1 <- read_excel("TANIwith ESP2010.xlsm", sheet = "Summary", range = "A355:A385", col_names = "month_day")
dfrwtanioct1$month_day <- as.Date(as.character((dfrwtanioct1$month_day)))
dfrwtanioct2 <- read_excel("TANIwith ESP2010.xlsm", sheet = "Summary", range = "H355:H385", col_names = "y_2010")
dfrwtanioct <- cbind(dfrwtanioct1, dfrwtanioct2)
dfrwtanioct3 <- read_excel("TANIwith ESP2011.xlsm", sheet = "Summary", range = "H355:H385", col_names = "y_2011")
dfrwtanioct <- cbind(dfrwtanioct, dfrwtanioct3)
dfrwtanioct4 <- read_excel("TANIwith ESP2012.xlsm", sheet = "Summary", range = "I355:I385", col_names = "y_2012")
dfrwtanioct <- cbind(dfrwtanioct, dfrwtanioct4)
dfrwtanioct5 <- read_excel("TANIwith ESP2013.xlsm", sheet = "Summary", range = "I355:I385", col_names = "y_2013")
dfrwtanioct <- cbind(dfrwtanioct, dfrwtanioct5)
dfrwtanioct6 <- read_excel("TANIwith ESP2014.xlsm", sheet = "Summary", range = "I355:I385", col_names = "y_2014")
dfrwtanioct <- cbind(dfrwtanioct, dfrwtanioct6)
dfrwtanioct7 <- read_excel("TANIwith ESP2015.xlsm", sheet = "Summary", range = "I355:I385", col_names = "y_2015")
dfrwtanioct <- cbind(dfrwtanioct, dfrwtanioct7)
dfrwtanioct8 <- read_excel("TANIwith ESP2016.xlsm", sheet = "Summary", range = "I355:I385", col_names = "y_2016")
dfrwtanioct <- cbind(dfrwtanioct, dfrwtanioct8)
dfrwtanioct9 <- read_excel("TANIwith ESP2017.xlsm", sheet = "Summary", range = "I355:I385", col_names = "y_2017")
dfrwtanioct <- cbind(dfrwtanioct, dfrwtanioct9)
dfrwtanioct10 <- read_excel("TANIwithWSP2018.xlsm", sheet = "Summary", range = "K355:K385", col_names = "y_2018")
dfrwtanioct <- cbind(dfrwtanioct, dfrwtanioct10)
dfrwtanioct11 <- read_excel("TANIwithWSP2019.xlsm", sheet = "Summary", range = "K355:K385", col_names = "y_2019")
dfrwtanioct <- cbind(dfrwtanioct, dfrwtanioct11)
dfrwtanioct12 <- read_excel("TANIwithWSP2020.xlsm", sheet = "Summary", range = "K355:K385", col_names = "y_2020")
dfrwtanioct <- cbind(dfrwtanioct, dfrwtanioct12)
dfrwtanioct13 <- read_excel("TANIwithWSP2021.xlsm", sheet = "Summary", range = "K355:K385", col_names = "y_2021")
dfrwtanioct <- cbind(dfrwtanioct, dfrwtanioct13)
#
dfrwtanifinal <- rbind(dfrwtanifinal, dfrwtanioct)
#
# Load the data for November into dataframe dfrwtanifinal
dfrwtaninov1 <- read_excel("TANIwith ESP2011.xlsm", sheet = "Summary", range = "A9:A38", col_names = "month_day")
dfrwtaninov1$month_day <- as.Date(as.character((dfrwtaninov1$month_day)))
dfrwtaninov2 <- read_excel("TANIwith ESP2011.xlsm", sheet = "Summary", range = "H9:H38", col_names = "y_2010")
dfrwtaninov <- cbind(dfrwtaninov1, dfrwtaninov2)
dfrwtaninov3 <- read_excel("TANIwith ESP2012.xlsm", sheet = "Summary", range = "I9:I38", col_names = "y_2011")
dfrwtaninov <- cbind(dfrwtaninov, dfrwtaninov3)
dfrwtaninov4 <- read_excel("TANIwith ESP2013.xlsm", sheet = "Summary", range = "I9:I38", col_names = "y_2012")
dfrwtaninov <- cbind(dfrwtaninov, dfrwtaninov4)
dfrwtaninov5 <- read_excel("TANIwith ESP2014.xlsm", sheet = "Summary", range = "I9:I38", col_names = "y_2013")
dfrwtaninov <- cbind(dfrwtaninov, dfrwtaninov5)
dfrwtaninov6 <- read_excel("TANIwith ESP2015.xlsm", sheet = "Summary", range = "I9:I38", col_names = "y_2014")
dfrwtaninov <- cbind(dfrwtaninov, dfrwtaninov6)
dfrwtaninov7 <- read_excel("TANIwith ESP2016.xlsm", sheet = "Summary", range = "I9:I38", col_names = "y_2015")
dfrwtaninov <- cbind(dfrwtaninov, dfrwtaninov7)
dfrwtaninov8 <- read_excel("TANIwith ESP2017.xlsm", sheet = "Summary", range = "I9:I38", col_names = "y_2016")
dfrwtaninov <- cbind(dfrwtaninov, dfrwtaninov8)
dfrwtaninov9 <- read_excel("TANIwithWSP2018.xlsm", sheet = "Summary", range = "K9:K38", col_names = "y_2017")
dfrwtaninov <- cbind(dfrwtaninov, dfrwtaninov9)
dfrwtaninov10 <- read_excel("TANIwithWSP2019.xlsm", sheet = "Summary", range = "K9:K38", col_names = "y_2018")
dfrwtaninov <- cbind(dfrwtaninov, dfrwtaninov10)
dfrwtaninov11 <- read_excel("TANIwithWSP2020.xlsm", sheet = "Summary", range = "K9:K38", col_names = "y_2019")
dfrwtaninov <- cbind(dfrwtaninov, dfrwtaninov11)
dfrwtaninov12 <- read_excel("TANIwithWSP2021.xlsm", sheet = "Summary", range = "K9:K38", col_names = "y_2020")
dfrwtaninov <- cbind(dfrwtaninov, dfrwtaninov12)
dfrwtaninov13 <- read_excel("TANIwithWSP2022.xlsm", sheet = "Summary", range = "K9:K38", col_names = "y_2021")
dfrwtaninov <- cbind(dfrwtaninov, dfrwtaninov13)
#
dfrwtanifinal <- rbind(dfrwtanifinal, dfrwtaninov)
#
# Load the data for December into dataframe dfrwtanifinal
dfrwtanidec1 <- read_excel("TANIwith ESP2011.xlsm", sheet = "Summary", range = "A40:A70", col_names = "month_day")
dfrwtanidec1$month_day <- as.Date(as.character((dfrwtanidec1$month_day)))
dfrwtanidec2 <- read_excel("TANIwith ESP2011.xlsm", sheet = "Summary", range = "H40:H70", col_names = "y_2010")
dfrwtanidec <- cbind(dfrwtanidec1, dfrwtanidec2)
dfrwtanidec3 <- read_excel("TANIwith ESP2012.xlsm", sheet = "Summary", range = "I40:I70", col_names = "y_2011")
dfrwtanidec <- cbind(dfrwtanidec, dfrwtanidec3)
dfrwtanidec4 <- read_excel("TANIwith ESP2013.xlsm", sheet = "Summary", range = "I40:I70", col_names = "y_2012")
dfrwtanidec <- cbind(dfrwtanidec, dfrwtanidec4)
dfrwtanidec5 <- read_excel("TANIwith ESP2014.xlsm", sheet = "Summary", range = "I40:I70", col_names = "y_2013")
dfrwtanidec <- cbind(dfrwtanidec, dfrwtanidec5)
dfrwtanidec6 <- read_excel("TANIwith ESP2015.xlsm", sheet = "Summary", range = "I40:I70", col_names = "y_2014")
dfrwtanidec <- cbind(dfrwtanidec, dfrwtanidec6)
dfrwtanidec7 <- read_excel("TANIwith ESP2016.xlsm", sheet = "Summary", range = "I40:I70", col_names = "y_2015")
dfrwtanidec <- cbind(dfrwtanidec, dfrwtanidec7)
dfrwtanidec8 <- read_excel("TANIwith ESP2017.xlsm", sheet = "Summary", range = "I40:I70", col_names = "y_2016")
dfrwtanidec <- cbind(dfrwtanidec, dfrwtanidec8)
dfrwtanidec9 <- read_excel("TANIwithWSP2018.xlsm", sheet = "Summary", range = "K40:K70", col_names = "y_2017")
dfrwtanidec <- cbind(dfrwtanidec, dfrwtanidec9)
dfrwtanidec10 <- read_excel("TANIwithWSP2019.xlsm", sheet = "Summary", range = "K40:K70", col_names = "y_2018")
dfrwtanidec <- cbind(dfrwtanidec, dfrwtanidec10)
dfrwtanidec11 <- read_excel("TANIwithWSP2020.xlsm", sheet = "Summary", range = "K40:K70", col_names = "y_2019")
dfrwtanidec <- cbind(dfrwtanidec, dfrwtanidec11)
dfrwtanidec12 <- read_excel("TANIwithWSP2021.xlsm", sheet = "Summary", range = "K40:K70", col_names = "y_2020")
dfrwtanidec <- cbind(dfrwtanidec, dfrwtanidec12)
dfrwtanidec13 <- read_excel("TANIwithWSP2022.xlsm", sheet = "Summary", range = "K40:K70", col_names = "y_2021")
dfrwtanidec <- cbind(dfrwtanidec, dfrwtanidec13)
#
dfrwtanifinal <- rbind(dfrwtanifinal, dfrwtanidec)
#
# The values from the workbooks are negative, change them to positive. They are inflows to the treatment plant and come in negative because they are outflows from the reservoir.
# 
dfrwtanifinal[, 2:13] <- dfrwtanifinal[, 2:13] * -1
#
# Replace all NA values with 0
#
dfrwtanifinal[, 2:13] <- lapply(dfrwtanifinal[, 2:13], function(x) replace(x, is.na(x), 0))
#
# Compute the mean for each day over all the years ignoring zeros
#
dfrwtanifinal$mean = apply(dfrwtanifinal[, 2:13], 1, function(x) mean(x[x>0]))
#
# Computing the mean on February 29th with all zero values for WGL  returns NaN. Hoping that this will clear up when there are not treatment values = 0 with all workbooks.
# 
# Compute the median for each day over all the years ignoring zeros
#
dfrwtanifinal$median = apply(dfrwtanifinal[, 2:13], 1, function(x) median(x[x>0]))
#
# Computing the median on February 29th with all zero values for WGL  returns NA. Hoping that this will clear up when there are not treatment values = 0 with all workbooks.
#
# Determine the maximum by day over all of the days ignoring zeros
dfrwtanifinal$maximum <- apply(dfrwtanifinal[, 2:13], 1, function(x) max(x[x>=0]))
# 
# Determine the maximum by day over all of the days ignoring zeros
dfrwtanifinal$minimum <- apply(dfrwtanifinal[, 2:13], 1, function(x) min(x[x>=0]))
#

#
View(dfrwtanifinal)
# x <- memory.size()
# View(x)
# y <- memory.size(max = TRUE)
# View(y)